name: flutter_ecommerce_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons pentru stiluri de iconițe specifice iOS
  cupertino_icons: ^1.0.3

  # Google Fonts pentru utilizarea fonturilor Google
  google_fonts: ^2.1.0

  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  google_sign_in: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/

  # Pentru a adăuga fonturi personalizate, adaugă-le în secțiunea de mai jos.
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
